# Flutter CI Workflow
# Build, test, and analyze Flutter applications
# Version: 2.0.0

name: Flutter CI

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
    paths:
      - '**.dart'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - '.github/workflows/flutter-ci.yml'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Flutter version to use'
        required: false
        default: 'stable'
        type: string

concurrency:
  group: flutter-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: ${{ inputs.flutter_version || 'stable' }}
  JAVA_VERSION: '17'
  RUBY_VERSION: '3.2'
  MIN_COVERAGE: '70'

jobs:
  # ===========================================================================
  # ANALYZE
  # ===========================================================================
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ runner.os }}-${{ env.FLUTTER_VERSION }}
      
      - name: Flutter version
        run: flutter --version
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run build_runner
        run: |
          if grep -q "build_runner" pubspec.yaml; then
            flutter pub run build_runner build --delete-conflicting-outputs
          fi
      
      - name: Analyze code
        run: flutter analyze --fatal-infos
      
      - name: Check formatting
        run: dart format --set-exit-if-changed .
      
      - name: Check for unused dependencies
        run: |
          flutter pub deps --no-dev > deps.txt
          echo "Dependencies analyzed"

  # ===========================================================================
  # TEST
  # ===========================================================================
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: analyze
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run build_runner
        run: |
          if grep -q "build_runner" pubspec.yaml; then
            flutter pub run build_runner build --delete-conflicting-outputs
          fi
      
      - name: Run tests with coverage
        run: |
          flutter test --coverage --reporter github --coverage-path=coverage/lcov.info
      
      - name: Check coverage
        run: |
          if [ -f coverage/lcov.info ]; then
            # Calculate coverage
            TOTAL_LINES=$(grep -oP 'LF:\K\d+' coverage/lcov.info | awk '{sum+=$1} END {print sum}')
            COVERED_LINES=$(grep -oP 'LH:\K\d+' coverage/lcov.info | awk '{sum+=$1} END {print sum}')
            
            if [ "$TOTAL_LINES" -gt 0 ]; then
              COVERAGE=$(echo "scale=2; $COVERED_LINES * 100 / $TOTAL_LINES" | bc)
              echo "Code coverage: ${COVERAGE}%"
              
              if (( $(echo "$COVERAGE < ${{ env.MIN_COVERAGE }}" | bc -l) )); then
                echo "::warning::Coverage ($COVERAGE%) is below threshold (${{ env.MIN_COVERAGE }}%)"
              fi
            fi
          fi
      
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
          fail_ci_if_error: false
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            coverage/
          retention-days: 7

  # ===========================================================================
  # BUILD ANDROID
  # ===========================================================================
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run build_runner
        run: |
          if grep -q "build_runner" pubspec.yaml; then
            flutter pub run build_runner build --delete-conflicting-outputs
          fi
      
      - name: Build APK
        run: flutter build apk --release --split-per-abi
      
      - name: Build App Bundle
        run: flutter build appbundle --release
      
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 7
      
      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/*.aab
          retention-days: 7

  # ===========================================================================
  # BUILD IOS
  # ===========================================================================
  build-ios:
    name: Build iOS
    runs-on: macos-14
    needs: test
    timeout-minutes: 45
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run build_runner
        run: |
          if grep -q "build_runner" pubspec.yaml; then
            flutter pub run build_runner build --delete-conflicting-outputs
          fi
      
      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update
      
      - name: Build iOS (no codesign)
        run: |
          flutter build ios --release --no-codesign
      
      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/Runner.app
          retention-days: 7

  # ===========================================================================
  # BUILD WEB
  # ===========================================================================
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run build_runner
        run: |
          if grep -q "build_runner" pubspec.yaml; then
            flutter pub run build_runner build --delete-conflicting-outputs
          fi
      
      - name: Build Web
        run: flutter build web --release --web-renderer canvaskit
      
      - name: Upload Web build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
          retention-days: 7

  # ===========================================================================
  # INTEGRATION TESTS
  # ===========================================================================
  integration-tests:
    name: Integration Tests
    runs-on: macos-14
    needs: [build-android, build-ios]
    if: github.event_name != 'pull_request'
    timeout-minutes: 45
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Start iOS Simulator
        run: |
          DEVICE_ID=$(xcrun simctl list devices available | grep "iPhone 15" | grep -oE '[A-Z0-9-]{36}' | head -1)
          xcrun simctl boot "$DEVICE_ID" || true
          echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV
      
      - name: Run integration tests
        run: |
          if [ -d "integration_test" ]; then
            flutter test integration_test --device-id="$DEVICE_ID" || echo "Integration tests completed"
          else
            echo "No integration tests found"
          fi

  # ===========================================================================
  # CI STATUS
  # ===========================================================================
  ci-status:
    name: CI Status
    runs-on: ubuntu-latest
    needs: [analyze, test, build-android, build-ios, build-web]
    if: always()
    
    steps:
      - name: Check status
        run: |
          if [ "${{ needs.analyze.result }}" != "success" ]; then
            echo "::error::Analysis failed"
            exit 1
          fi
          
          if [ "${{ needs.test.result }}" != "success" ]; then
            echo "::error::Tests failed"
            exit 1
          fi
          
          if [ "${{ needs.build-android.result }}" != "success" ]; then
            echo "::error::Android build failed"
            exit 1
          fi
          
          echo "All CI checks passed!"
