# Flutter iOS Release Workflow
# Build and deploy Flutter iOS apps to App Store
# Version: 2.0.0

name: Flutter iOS Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ios'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.2.3)'
        required: true
        type: string
      destination:
        description: 'Release destination'
        required: true
        default: 'testflight'
        type: choice
        options:
          - testflight
          - app-store
      submit_for_review:
        description: 'Submit for App Store review'
        required: false
        default: 'false'
        type: boolean

concurrency:
  group: flutter-ios-release
  cancel-in-progress: false

env:
  FLUTTER_VERSION: 'stable'
  XCODE_VERSION: '15.2'
  RUBY_VERSION: '3.2'

jobs:
  # ===========================================================================
  # VALIDATE
  # ===========================================================================
  validate:
    name: Validate Release
    runs-on: macos-14
    timeout-minutes: 10
    
    outputs:
      version: ${{ steps.version.outputs.version }}
      build_number: ${{ steps.version.outputs.build_number }}
      destination: ${{ steps.destination.outputs.destination }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Determine version
        id: version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/v}"
            VERSION="${VERSION%-ios}"
          fi
          
          # Validate semantic version
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid version format: $VERSION"
            exit 1
          fi
          
          BUILD_NUMBER="${{ github.run_number }}"
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
          echo "Releasing version: $VERSION+$BUILD_NUMBER"
      
      - name: Determine destination
        id: destination
        run: |
          DESTINATION="${{ inputs.destination }}"
          if [ -z "$DESTINATION" ]; then
            DESTINATION="testflight"
          fi
          echo "destination=$DESTINATION" >> $GITHUB_OUTPUT

  # ===========================================================================
  # BUILD
  # ===========================================================================
  build:
    name: Build iOS
    runs-on: macos-14
    needs: validate
    timeout-minutes: 60
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Select Xcode version
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app
          xcodebuild -version
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run build_runner
        run: |
          if grep -q "build_runner" pubspec.yaml; then
            flutter pub run build_runner build --delete-conflicting-outputs
          fi
      
      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update
      
      - name: Setup code signing
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_TOKEN }}
        run: |
          # Create keychain
          KEYCHAIN_PATH=$RUNNER_TEMP/signing.keychain-db
          KEYCHAIN_PASSWORD=$(openssl rand -base64 32)
          
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security list-keychains -d user -s "$KEYCHAIN_PATH" login.keychain
          
          # Install Fastlane
          cd ios
          bundle install
          
          # Sync certificates
          bundle exec fastlane match appstore \
            --readonly true \
            --keychain_name "$KEYCHAIN_PATH" \
            --keychain_password "$KEYCHAIN_PASSWORD"
      
      - name: Update version
        run: |
          VERSION="${{ needs.validate.outputs.version }}"
          BUILD_NUMBER="${{ needs.validate.outputs.build_number }}"
          
          # Update pubspec.yaml
          sed -i '' "s/^version: .*/version: $VERSION+$BUILD_NUMBER/" pubspec.yaml
          
          # Update iOS project
          cd ios
          agvtool new-marketing-version "$VERSION"
          agvtool new-version -all "$BUILD_NUMBER"
      
      - name: Build iOS
        run: |
          flutter build ios --release \
            --build-name=${{ needs.validate.outputs.version }} \
            --build-number=${{ needs.validate.outputs.build_number }} \
            --obfuscate \
            --split-debug-info=build/debug-info
      
      - name: Create IPA
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          cd ios
          
          # Create export options
          cat > ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>$TEAM_ID</string>
            <key>uploadSymbols</key>
            <true/>
            <key>destination</key>
            <string>upload</string>
          </dict>
          </plist>
          EOF
          
          # Archive
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath ../build/Runner.xcarchive \
            archive \
            | xcpretty
          
          # Export
          xcodebuild -exportArchive \
            -archivePath ../build/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath ../build/ios \
            | xcpretty
      
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-ipa
          path: build/ios/*.ipa
          retention-days: 30
      
      - name: Upload dSYMs
        uses: actions/upload-artifact@v4
        with:
          name: ios-dsyms
          path: build/Runner.xcarchive/dSYMs
          retention-days: 90
      
      - name: Upload debug info
        uses: actions/upload-artifact@v4
        with:
          name: ios-debug-symbols
          path: build/debug-info/
          retention-days: 90

  # ===========================================================================
  # TEST
  # ===========================================================================
  test:
    name: Release Tests
    runs-on: macos-14
    needs: validate
    timeout-minutes: 20
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run tests
        run: flutter test --reporter github

  # ===========================================================================
  # DEPLOY
  # ===========================================================================
  deploy:
    name: Deploy to ${{ needs.validate.outputs.destination }}
    runs-on: macos-14
    needs: [validate, build, test]
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      
      - name: Download IPA
        uses: actions/download-artifact@v4
        with:
          name: ios-release-ipa
          path: build/
      
      - name: Setup App Store Connect API key
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo "$APP_STORE_CONNECT_API_KEY_CONTENT" | base64 --decode > ~/.appstoreconnect/private_keys/AuthKey_${APP_STORE_CONNECT_API_KEY_ID}.p8
      
      - name: Upload to App Store Connect
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        run: |
          IPA_FILE=$(find build -name "*.ipa" | head -1)
          
          xcrun altool --upload-app \
            --file "$IPA_FILE" \
            --type ios \
            --apiKey "$APP_STORE_CONNECT_API_KEY_ID" \
            --apiIssuer "$APP_STORE_CONNECT_ISSUER_ID"
      
      - name: Distribute to TestFlight
        if: ${{ needs.validate.outputs.destination == 'testflight' }}
        run: |
          cd ios
          bundle install
          
          # Generate changelog
          CHANGELOG=$(git log --pretty=format:"• %s" -10 --no-merges | head -c 4000)
          
          bundle exec fastlane pilot distribute \
            --changelog "$CHANGELOG" \
            --groups "Internal Testers" \
            --skip_waiting_for_build_processing true
      
      - name: Submit for Review
        if: ${{ inputs.submit_for_review == 'true' && needs.validate.outputs.destination == 'app-store' }}
        run: |
          cd ios
          bundle install
          
          bundle exec fastlane deliver \
            --submit_for_review true \
            --automatic_release false \
            --skip_screenshots true \
            --skip_metadata true

  # ===========================================================================
  # POST-RELEASE
  # ===========================================================================
  post-release:
    name: Post-Release Tasks
    runs-on: ubuntu-latest
    needs: [validate, deploy]
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Create Git tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          VERSION="${{ needs.validate.outputs.version }}"
          
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          if ! git rev-parse "v$VERSION-ios" >/dev/null 2>&1; then
            git tag -a "v$VERSION-ios" -m "iOS release v$VERSION"
            git push origin "v$VERSION-ios"
          fi
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.validate.outputs.version }}-ios
          name: iOS v${{ needs.validate.outputs.version }}
          body: |
            ## iOS Release v${{ needs.validate.outputs.version }}
            
            Build: ${{ needs.validate.outputs.build_number }}
            Destination: ${{ needs.validate.outputs.destination }}
          draft: false
          prerelease: ${{ needs.validate.outputs.destination == 'testflight' }}
      
      - name: Notify Slack
        if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "iOS v${{ needs.validate.outputs.version }} released to ${{ needs.validate.outputs.destination }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Flutter iOS Release*\n\nVersion: `${{ needs.validate.outputs.version }}`\nBuild: `${{ needs.validate.outputs.build_number }}`\nDestination: `${{ needs.validate.outputs.destination }}`"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # ===========================================================================
  # UPLOAD DSYMS
  # ===========================================================================
  upload-dsyms:
    name: Upload dSYMs
    runs-on: macos-14
    needs: [validate, build, deploy]
    timeout-minutes: 15
    
    steps:
      - name: Download dSYMs
        uses: actions/download-artifact@v4
        with:
          name: ios-dsyms
          path: dSYMs/
      
      - name: Upload to Crashlytics
        if: ${{ secrets.FIREBASE_APP_ID_IOS != '' }}
        run: |
          curl -sL https://firebase.tools | bash
          
          firebase crashlytics:symbols:upload \
            --app="${{ secrets.FIREBASE_APP_ID_IOS }}" \
            dSYMs/
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
