# Flutter Android Release Workflow
# Build and deploy Flutter Android apps to Google Play Store
# Version: 2.0.0

name: Flutter Android Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-android'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.2.3)'
        required: true
        type: string
      track:
        description: 'Release track'
        required: true
        default: 'internal'
        type: choice
        options:
          - internal
          - alpha
          - beta
          - production
      rollout:
        description: 'Rollout percentage (production only)'
        required: false
        default: '100'
        type: string

concurrency:
  group: flutter-android-release
  cancel-in-progress: false

env:
  FLUTTER_VERSION: 'stable'
  JAVA_VERSION: '17'
  RUBY_VERSION: '3.2'

jobs:
  # ===========================================================================
  # VALIDATE
  # ===========================================================================
  validate:
    name: Validate Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    outputs:
      version: ${{ steps.version.outputs.version }}
      build_number: ${{ steps.version.outputs.build_number }}
      track: ${{ steps.track.outputs.track }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Determine version
        id: version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/v}"
            VERSION="${VERSION%-android}"
          fi
          
          # Validate semantic version
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid version format: $VERSION"
            exit 1
          fi
          
          BUILD_NUMBER="${{ github.run_number }}"
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
          echo "Releasing version: $VERSION+$BUILD_NUMBER"
      
      - name: Determine track
        id: track
        run: |
          TRACK="${{ inputs.track }}"
          if [ -z "$TRACK" ]; then
            TRACK="internal"
          fi
          echo "track=$TRACK" >> $GITHUB_OUTPUT
          echo "Release track: $TRACK"

  # ===========================================================================
  # BUILD
  # ===========================================================================
  build:
    name: Build Android
    runs-on: ubuntu-latest
    needs: validate
    timeout-minutes: 45
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run build_runner
        run: |
          if grep -q "build_runner" pubspec.yaml; then
            flutter pub run build_runner build --delete-conflicting-outputs
          fi
      
      - name: Setup keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_PROPERTIES: ${{ secrets.ANDROID_KEYSTORE_PROPERTIES }}
        run: |
          # Decode keystore
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/release-keystore.jks
          
          # Create key.properties
          echo "$KEYSTORE_PROPERTIES" > android/key.properties
      
      - name: Update version
        run: |
          VERSION="${{ needs.validate.outputs.version }}"
          BUILD_NUMBER="${{ needs.validate.outputs.build_number }}"
          
          # Update pubspec.yaml version
          sed -i "s/^version: .*/version: $VERSION+$BUILD_NUMBER/" pubspec.yaml
      
      - name: Build App Bundle
        run: |
          flutter build appbundle --release \
            --build-name=${{ needs.validate.outputs.version }} \
            --build-number=${{ needs.validate.outputs.build_number }} \
            --obfuscate \
            --split-debug-info=build/debug-info
      
      - name: Build APK
        run: |
          flutter build apk --release \
            --split-per-abi \
            --build-name=${{ needs.validate.outputs.version }} \
            --build-number=${{ needs.validate.outputs.build_number }} \
            --obfuscate \
            --split-debug-info=build/debug-info
      
      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: android-release-aab
          path: build/app/outputs/bundle/release/*.aab
          retention-days: 30
      
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: build/app/outputs/flutter-apk/*-release.apk
          retention-days: 30
      
      - name: Upload debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-symbols
          path: build/debug-info/
          retention-days: 90

  # ===========================================================================
  # TEST
  # ===========================================================================
  test:
    name: Release Tests
    runs-on: ubuntu-latest
    needs: validate
    timeout-minutes: 20
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run tests
        run: flutter test --reporter github

  # ===========================================================================
  # DEPLOY
  # ===========================================================================
  deploy:
    name: Deploy to Google Play
    runs-on: ubuntu-latest
    needs: [validate, build, test]
    timeout-minutes: 30
    environment:
      name: production
      url: https://play.google.com/store/apps/details?id=${{ secrets.ANDROID_PACKAGE_NAME }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      
      - name: Download App Bundle
        uses: actions/download-artifact@v4
        with:
          name: android-release-aab
          path: build/
      
      - name: Setup Google Play credentials
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
        run: |
          echo "$GOOGLE_PLAY_JSON_KEY" > google-play-key.json
      
      - name: Generate changelog
        id: changelog
        run: |
          # Get recent commits for changelog
          CHANGELOG=$(git log --pretty=format:"• %s" -10 --no-merges | head -c 500)
          
          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="Bug fixes and performance improvements"
          fi
          
          mkdir -p fastlane/metadata/android/en-US/changelogs
          echo "$CHANGELOG" > "fastlane/metadata/android/en-US/changelogs/${{ needs.validate.outputs.build_number }}.txt"
          
          echo "changelog=$CHANGELOG" >> $GITHUB_OUTPUT
      
      - name: Deploy to Google Play
        env:
          SUPPLY_JSON_KEY: google-play-key.json
          SUPPLY_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
        run: |
          AAB_FILE=$(find build -name "*.aab" | head -1)
          TRACK="${{ needs.validate.outputs.track }}"
          ROLLOUT="${{ inputs.rollout || '100' }}"
          
          if [ "$TRACK" == "production" ] && [ "$ROLLOUT" != "100" ]; then
            # Staged rollout
            bundle exec fastlane supply \
              --aab "$AAB_FILE" \
              --track "$TRACK" \
              --rollout "$(echo "scale=2; $ROLLOUT / 100" | bc)" \
              --skip_upload_metadata true \
              --skip_upload_images true \
              --skip_upload_screenshots true
          else
            # Full release
            bundle exec fastlane supply \
              --aab "$AAB_FILE" \
              --track "$TRACK" \
              --skip_upload_metadata true \
              --skip_upload_images true \
              --skip_upload_screenshots true
          fi
      
      - name: Cleanup credentials
        if: always()
        run: rm -f google-play-key.json

  # ===========================================================================
  # POST-RELEASE
  # ===========================================================================
  post-release:
    name: Post-Release Tasks
    runs-on: ubuntu-latest
    needs: [validate, deploy]
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Create Git tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          VERSION="${{ needs.validate.outputs.version }}"
          
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          if ! git rev-parse "v$VERSION-android" >/dev/null 2>&1; then
            git tag -a "v$VERSION-android" -m "Android release v$VERSION"
            git push origin "v$VERSION-android"
          fi
      
      - name: Generate release notes
        id: notes
        run: |
          VERSION="${{ needs.validate.outputs.version }}"
          BUILD="${{ needs.validate.outputs.build_number }}"
          TRACK="${{ needs.validate.outputs.track }}"
          
          CHANGELOG=$(git log --pretty=format:"- %s" -20 --no-merges)
          
          cat > release-notes.md << EOF
          ## Android Release v$VERSION ($BUILD)
          
          **Track:** $TRACK
          **Package:** ${{ secrets.ANDROID_PACKAGE_NAME }}
          
          ### Changes
          $CHANGELOG
          EOF
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.validate.outputs.version }}-android
          name: Android v${{ needs.validate.outputs.version }}
          body_path: release-notes.md
          draft: false
          prerelease: ${{ needs.validate.outputs.track != 'production' }}
      
      - name: Notify Slack
        if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "Android v${{ needs.validate.outputs.version }} released to ${{ needs.validate.outputs.track }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Flutter Android Release*\n\nVersion: `${{ needs.validate.outputs.version }}`\nBuild: `${{ needs.validate.outputs.build_number }}`\nTrack: `${{ needs.validate.outputs.track }}`"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # ===========================================================================
  # UPLOAD SYMBOLS
  # ===========================================================================
  upload-symbols:
    name: Upload Debug Symbols
    runs-on: ubuntu-latest
    needs: [validate, build, deploy]
    timeout-minutes: 15
    
    steps:
      - name: Download debug symbols
        uses: actions/download-artifact@v4
        with:
          name: android-debug-symbols
          path: debug-info/
      
      - name: Upload to Crashlytics
        if: ${{ secrets.FIREBASE_APP_ID_ANDROID != '' }}
        run: |
          curl -sL https://firebase.tools | bash
          
          firebase crashlytics:symbols:upload \
            --app="${{ secrets.FIREBASE_APP_ID_ANDROID }}" \
            debug-info/
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
