# Flutter Web Build and Deploy Workflow
# Build and deploy Flutter web apps to various hosting platforms
# Version: 2.0.0

name: Flutter Web Deploy

on:
  push:
    branches:
      - main
    paths:
      - '**.dart'
      - 'pubspec.yaml'
      - 'web/**'
      - '.github/workflows/flutter-web.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      renderer:
        description: 'Web renderer'
        required: false
        default: 'canvaskit'
        type: choice
        options:
          - canvaskit
          - html
          - auto

concurrency:
  group: flutter-web-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: 'stable'
  NODE_VERSION: '20'

jobs:
  # ===========================================================================
  # BUILD
  # ===========================================================================
  build:
    name: Build Web
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    outputs:
      version: ${{ steps.version.outputs.version }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run build_runner
        run: |
          if grep -q "build_runner" pubspec.yaml; then
            flutter pub run build_runner build --delete-conflicting-outputs
          fi
      
      - name: Get version
        id: version
        run: |
          VERSION=$(grep "^version:" pubspec.yaml | sed 's/version: //' | cut -d'+' -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Build Web
        run: |
          RENDERER="${{ inputs.renderer || 'canvaskit' }}"
          
          flutter build web \
            --release \
            --web-renderer "$RENDERER" \
            --pwa-strategy offline-first \
            --source-maps
          
          # Add build info
          echo "{\"version\":\"${{ steps.version.outputs.version }}\",\"build\":\"${{ github.run_number }}\",\"date\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > build/web/version.json
      
      - name: Optimize assets
        run: |
          # Compress JavaScript
          find build/web -name "*.js" -type f | while read file; do
            if command -v terser &> /dev/null; then
              terser "$file" --compress --mangle -o "$file.min"
              mv "$file.min" "$file"
            fi
          done
          
          # Compress HTML
          find build/web -name "*.html" -type f | while read file; do
            if command -v html-minifier &> /dev/null; then
              html-minifier --collapse-whitespace --remove-comments "$file" -o "$file"
            fi
          done
      
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
          retention-days: 7

  # ===========================================================================
  # DEPLOY TO FIREBASE HOSTING
  # ===========================================================================
  deploy-firebase:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    needs: build
    if: ${{ secrets.FIREBASE_PROJECT_ID != '' }}
    timeout-minutes: 15
    environment:
      name: ${{ inputs.environment || 'staging' }}
      url: ${{ steps.deploy.outputs.url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build/web
      
      - name: Deploy to Firebase Hosting
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: ${{ inputs.environment == 'production' && 'live' || 'staging' }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

  # ===========================================================================
  # DEPLOY TO GITHUB PAGES
  # ===========================================================================
  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.environment == 'production' || github.ref == 'refs/heads/main' }}
    timeout-minutes: 10
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build/web
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # ===========================================================================
  # DEPLOY TO NETLIFY
  # ===========================================================================
  deploy-netlify:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    needs: build
    if: ${{ secrets.NETLIFY_AUTH_TOKEN != '' }}
    timeout-minutes: 10
    
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build/web
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: build/web
          production-deploy: ${{ inputs.environment == 'production' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy v${{ needs.build.outputs.version }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  # ===========================================================================
  # DEPLOY TO VERCEL
  # ===========================================================================
  deploy-vercel:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: build
    if: ${{ secrets.VERCEL_TOKEN != '' }}
    timeout-minutes: 10
    
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build/web
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install Vercel CLI
        run: npm install -g vercel
      
      - name: Deploy to Vercel
        run: |
          cd build/web
          
          if [ "${{ inputs.environment }}" == "production" ]; then
            vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel --token=${{ secrets.VERCEL_TOKEN }}
          fi
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  # ===========================================================================
  # LIGHTHOUSE AUDIT
  # ===========================================================================
  lighthouse:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    needs: [build, deploy-firebase]
    if: always() && needs.deploy-firebase.result == 'success'
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            ${{ needs.deploy-firebase.outputs.url }}
          budgetPath: .github/lighthouse-budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
      
      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci
          retention-days: 14
