# iOS Nightly Build Workflow
# Scheduled nightly builds with comprehensive testing and reporting
# Version: 2.0.0

name: iOS Nightly Build

on:
  schedule:
    # Run at 2 AM UTC every weekday
    - cron: '0 2 * * 1-5'
  workflow_dispatch:
    inputs:
      full_test_suite:
        description: 'Run full test suite including UI tests'
        required: false
        default: 'true'
        type: boolean
      deploy_to_firebase:
        description: 'Deploy to Firebase App Distribution'
        required: false
        default: 'false'
        type: boolean

env:
  WORKSPACE_NAME: App.xcworkspace
  SCHEME_NAME: App
  XCODE_VERSION: '15.2'
  RUBY_VERSION: '3.2'

jobs:
  # ===========================================================================
  # NIGHTLY BUILD
  # ===========================================================================
  build:
    name: Nightly Build
    runs-on: macos-14
    timeout-minutes: 45
    
    outputs:
      version: ${{ steps.info.outputs.version }}
      build_number: ${{ steps.info.outputs.build_number }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      
      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec pod install --repo-update
      
      - name: Get build info
        id: info
        run: |
          VERSION=$(agvtool what-marketing-version -terse1 2>/dev/null || echo "1.0.0")
          DATE=$(date +%Y%m%d)
          BUILD_NUMBER="${DATE}.${{ github.run_number }}"
          
          agvtool new-version -all "$BUILD_NUMBER"
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
      
      - name: Build
        run: |
          set -o pipefail
          
          xcodebuild clean build \
            -workspace "${{ env.WORKSPACE_NAME }}" \
            -scheme "${{ env.SCHEME_NAME }}" \
            -configuration Debug \
            -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            | xcpretty --color
      
      - name: Archive build
        run: |
          mkdir -p build/Nightly
          
          # Create debug IPA for testing
          xcodebuild archive \
            -workspace "${{ env.WORKSPACE_NAME }}" \
            -scheme "${{ env.SCHEME_NAME }}" \
            -configuration Debug \
            -archivePath ./build/Nightly/App.xcarchive \
            -destination "generic/platform=iOS Simulator" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nightly-build
          path: build/Nightly
          retention-days: 7

  # ===========================================================================
  # FULL TEST SUITE
  # ===========================================================================
  test:
    name: Full Test Suite
    runs-on: macos-14
    needs: build
    if: ${{ inputs.full_test_suite != 'false' }}
    timeout-minutes: 90
    
    strategy:
      fail-fast: false
      matrix:
        test-type: [unit, ui, performance]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      
      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec pod install
      
      - name: Run tests
        run: |
          TEST_PLAN=""
          case "${{ matrix.test-type }}" in
            unit)
              TEST_PLAN="UnitTests"
              ;;
            ui)
              TEST_PLAN="UITests"
              ;;
            performance)
              TEST_PLAN="PerformanceTests"
              ;;
          esac
          
          set -o pipefail
          
          xcodebuild test \
            -workspace "${{ env.WORKSPACE_NAME }}" \
            -scheme "${{ env.SCHEME_NAME }}" \
            -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2" \
            -testPlan "$TEST_PLAN" \
            -resultBundlePath "./TestResults-${{ matrix.test-type }}.xcresult" \
            -enableCodeCoverage YES \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            | xcpretty --color --report junit --output "./test-results-${{ matrix.test-type }}.xml" || true
      
      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.test-type }}
          path: |
            test-results-*.xml
            TestResults-*.xcresult
          retention-days: 14

  # ===========================================================================
  # CODE ANALYSIS
  # ===========================================================================
  analyze:
    name: Code Analysis
    runs-on: macos-14
    needs: build
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install analysis tools
        run: |
          brew install swiftlint periphery
      
      - name: SwiftLint analysis
        run: |
          swiftlint analyze \
            --compiler-log-path build.log \
            --reporter json > swiftlint-report.json || true
      
      - name: Dead code detection
        run: |
          periphery scan \
            --workspace "${{ env.WORKSPACE_NAME }}" \
            --schemes "${{ env.SCHEME_NAME }}" \
            --format json > dead-code-report.json || true
      
      - name: Code metrics
        run: |
          echo "# Code Metrics Report" > metrics-report.md
          echo "" >> metrics-report.md
          echo "Generated: $(date)" >> metrics-report.md
          echo "" >> metrics-report.md
          
          # Line counts
          echo "## Line Counts" >> metrics-report.md
          echo "" >> metrics-report.md
          echo "| Type | Lines |" >> metrics-report.md
          echo "|------|-------|" >> metrics-report.md
          
          SWIFT_LINES=$(find . -name "*.swift" -not -path "./Pods/*" -exec cat {} + | wc -l)
          echo "| Swift | $SWIFT_LINES |" >> metrics-report.md
          
          TEST_LINES=$(find . -name "*Test*.swift" -exec cat {} + | wc -l)
          echo "| Tests | $TEST_LINES |" >> metrics-report.md
          
          # File counts
          echo "" >> metrics-report.md
          echo "## File Counts" >> metrics-report.md
          echo "" >> metrics-report.md
          
          SWIFT_FILES=$(find . -name "*.swift" -not -path "./Pods/*" | wc -l)
          echo "Swift files: $SWIFT_FILES" >> metrics-report.md
      
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: analysis-reports
          path: |
            swiftlint-report.json
            dead-code-report.json
            metrics-report.md
          retention-days: 30

  # ===========================================================================
  # GENERATE REPORT
  # ===========================================================================
  report:
    name: Generate Report
    runs-on: ubuntu-latest
    needs: [build, test, analyze]
    if: always()
    timeout-minutes: 10
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Generate summary
        run: |
          echo "# Nightly Build Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ needs.build.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Build:** ${{ needs.build.outputs.build_number }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          echo "## Job Status" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Build | ${{ needs.build.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Test | ${{ needs.test.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Analyze | ${{ needs.analyze.result }} |" >> $GITHUB_STEP_SUMMARY
      
      - name: Notify on failure
        if: ${{ needs.build.result == 'failure' || needs.test.result == 'failure' }}
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "Nightly build failed!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "iOS Nightly Build Failed"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Build:* ${{ needs.build.result }}\n*Test:* ${{ needs.test.result }}\n*Analyze:* ${{ needs.analyze.result }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Run"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
